---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown

version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@1

workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery

      - kitchen/dokken-single:
          name: debian-9
          suite: debian-9
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: centos-7
          suite: centos-7
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: centos-6
          suite: centos-6
          requires:
            *lint_and_unit
